### ISSUE TITLE
iOS version

### ISSUE THREAD

**Issue by yko** [hmara-info/language-settings-manager#20]
Build / test & coordinate the release of Safari/iOS version.
I assume, desktop version should work.

The work here is to figure out prerequisites to launch on Safari/iOS and cut tickets for any changes needed. I suspect, options.html might need tweaks to work well on mobile.

Important: this ticket is NOT to create a standalone iOS app. It's to research if existing extension could run on iOS and scope the work to make that happen. There is no intention to create and maintain a standalone native app at the moment.

**Comment by UnforbiddenYet** [comment]
Looking into this.

**Comment by UnforbiddenYet** [comment]
## Field notes

- The current `regex` for google does not work on iOS. When updated to `.*/search.*` extension filters out the search result just like on Mac.
- Haven't tested other websites (due to lack of experience).
- The setup process is even more complicated and cumbersome than on Mac.
- The UI (options page mostly) needs to be reworked to make sure it's mobile-first (i.e dropdowns are native select elements rather than custom dropdowns).

**Comment by UnforbiddenYet** [comment]
Okay, here's the outline of needed work to make this baby ready for release:

1. Update the Options page to be mobile-first and responsive:

**Comment by yko** [comment]
The work is done. Now there is more work to do 😅
